#%RAML 1.0 DataType

#This file is located at dataTypes/primitives/date.raml


type: string
description: |
  A date, or partial date (e.g. just year or year + month) as used in human communication. There is no time zone. Dates SHALL be valid dates
pattern: ^[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1]))?)?$
example: 1970-08-07
