#%RAML 1.0 DataType

#This file is located at dataTypes/primitives/decimal.raml


type: number
description: |
  Rational numbers that have a decimal representation. See below about the precision of the number
