#%RAML 1.0 DataType

#This file is located at dataTypes/primitives/uri.raml


type: string
description: |
  A Uniform Resource Identifier Reference (see: https://tools.ietf.org/html/rfc3986).
  Note: URIs are case sensitive. For UUID (urn:uuid:53fefa32-fcbb-4ff8-8a92-55ee120877b7) use all lowercase.
  URIs can be absolute or relative, and may have an optional fragment identifier.
