#%RAML 1.0 Library

uses:
  FHIR_element_types: ../elements/FHIR_element_types.raml
  FHIR_primitive_types: ../primitives/FHIR_primitive_types.raml

types:

  Entry:
    type: FHIR_element_types.BackboneElement
    properties:
      link?:
        type: array
        items:
          type: FHIR_element_types.BackboneElement
          properties:
            relation: string
            url: FHIR_primitive_types.uri
      fullUrl?: FHIR_primitive_types.uri
      search?:
        type: FHIR_element_types.BackboneElement
        properties:
          mode?:
            type: FHIR_primitive_types.code
            enum: [match, include, outcome]
          score?: FHIR_primitive_types.decimal
      request?:
        type: FHIR_element_types.BackboneElement
        properties:
          method:
            type: FHIR_primitive_types.code
            enum: [GET, PUT, POST, DELETE]
          url: FHIR_primitive_types.uri
          ifNoneMatch?: string
          ifModifiedSince?: FHIR_primitive_types.instant
          ifMatch: string
          ifNoneExist: string
      response?:
        type: object
        properties:
          status: string
          location?: FHIR_primitive_types.uri
          etag?: string
          lastModified?: FHIR_primitive_types.instant

  AllergyIntoleranceEntry:
    type: Entry
    properties:
      resource?: !include ../resources/AllergyIntolerance.raml

  AppointmentEntry:
    type: Entry
    properties:
      resource?: !include ../resources/Appointment.raml

  ConditionEntry:
    type: Entry
    properties:
      resource?: !include ../resources/Condition.raml

  DeviceEntry:
    type: Entry
    properties:
      resource?: !include ../resources/Device.raml

  EncounterEntry:
    type: Entry
    properties:
      resource?: !include ../resources/Encounter.raml

  MedicationEntry:
    type: Entry
    properties:
      resource?: !include ../resources/Medication.raml

  MedicationRequestEntry:
    type: Entry
    properties:
      resource?: !include ../resources/MedicationRequest.raml

  ObservationEntry:
    type: Entry
    properties:
      resource?: !include ../resources/Observation.raml

  PatientEntry:
    type: Entry
    properties:
      resource?: !include ../resources/Patient.raml

  PractitionerEntry:
    type: Entry
    properties:
      resource?: !include ../resources/Practitioner.raml

  ScheduleEntry:
    type: Entry
    properties:
      resource?: !include ../resources/Schedule.raml

  SlotEntry:
    type: Entry
    properties:
      resource?: !include ../resources/Slot.raml
