#%RAML 1.0 Library

uses:
  FHIR_element_types: ../elements/FHIR_element_types.raml
  FHIR_primitive_types: ../primitives/FHIR_primitive_types.raml

types:

  Entry:
    type: FHIR_element_types.BackboneElement
    properties:
      link?:
        type: array
        items:
          type: FHIR_element_types.BackboneElement
          properties:
            relation: string
            url: FHIR_primitive_types.uri
      fullUrl?: FHIR_primitive_types.uri
      search?:
        type: FHIR_element_types.BackboneElement
        properties:
          mode?:
            type: FHIR_primitive_types.code
            enum: [match, include, outcome]
          score?: FHIR_primitive_types.decimal
      request?:
        type: FHIR_element_types.BackboneElement
        properties:
          method:
            type: FHIR_primitive_types.code
            enum: [GET, PUT, POST, DELETE]
          url: FHIR_primitive_types.uri
          ifNoneMatch?: string
          ifModifiedSince?: FHIR_primitive_types.instant
          ifMatch: string
          ifNoneExist: string
      response?:
        type: object
        properties:
          status: string
          location?: FHIR_primitive_types.uri
          etag?: string
          lastModified?: FHIR_primitive_types.instant
  
  AllergyIntolerance: !include ../resources/AllergyIntolerance.raml
  Appointment: !include ../resources/Appointment.raml
  Condition: !include ../resources/Condition.raml
  Device: !include ../resources/Device.raml
  DomainResource: !include ../resources/DomainResource.raml
  Encounter: !include ../resources/Encounter.raml
  Medication: !include ../resources/Medication.raml
  MedicationRequest: !include ../resources/MedicationRequest.raml
  Observation: !include ../resources/Observation.raml
  Patient: !include ../resources/Patient.raml
  Practitioner: !include ../resources/Practitioner.raml
  Resource: !include ../resources/Resource.raml
  Schedule: !include ../resources/Schedule.raml
  Slot: !include ../resources/Slot.raml

  AllergyIntoleranceEntry:
    type: Entry
    properties:
      resource?: AllergyIntolerance

  AppointmentEntry:
    type: Entry
    properties:
      resource?: Appointment

  ConditionEntry:
    type: Entry
    properties:
      resource?: Condition

  DeviceEntry:
    type: Entry
    properties:
      resource?: Device

  EncounterEntry:
    type: Entry
    properties:
      resource?: Encounter

  MedicationEntry:
    type: Entry
    properties:
      resource?: Medication

  MedicationRequestEntry:
    type: Entry
    properties:
      resource?: MedicationRequest

  ObservationEntry:
    type: Entry
    properties:
      resource?: Observation

  PatientEntry:
    type: Entry
    properties:
      resource?: Patient

  PractitionerEntry:
    type: Entry
    properties:
      resource?: Practitioner

  ScheduleEntry:
    type: Entry
    properties:
      resource?: Schedule

  SlotEntry:
    type: Entry
    properties:
      resource?: Slot
