#%RAML 1.0 DataType

#This file is located at dataTypes/elements/Address.raml


type: !include ./Element.raml
description: |
  An address expressed using postal conventions (as opposed to GPS or other location definition formats).
  This data type may be used to convey addresses for use in delivering mail as well as for visiting locations which might not be valid for mail delivery.
  There are a variety of postal address formats defined around the world.
properties:
  use?:
    type: !include ../primitives/code.raml
    enum: [home, work, temp, old]
  type?:
    type: !include ../primitives/code.raml
    enum: [postal, physical, both]
  text?: string
  line?: string[]
  city?: string
  district?: string
  state?: string
  postalCode?: string
  country?: string
  period?: !include ./Period.raml
