#%RAML 1.0 DataType

#This file is located at dataTypes/elements/Annotation.raml


type: !include ./Element.raml
description: A text note which also contains information about who made the statement and when.
properties:
  authorReference: !include ./Reference.raml
  authorString: string
  time?: !include ../primitives/dateTime.raml
  text?: string
