#%RAML 1.0 DataType

#This file is located at dataTypes/elements/CodeableConcept.raml


type: !include ./Element.raml
description: |
  A CodeableConcept represents a value that is usually supplied by providing a reference to one or more terminologies or ontologies, but may also be defined by the provision of text.
  This is a common pattern in healthcare data.
properties:
  coding?:
    type: array
    items: !include ./Coding.raml
  text?: string
