#%RAML 1.0 DataType

#This file is located at dataTypes/elements/ContactPoint.raml


type: !include ./Element.raml
description: |
  Details for all kinds of technology-mediated contact points for a person or organization, including telephone, email, etc.
properties:
  system?:
    enum: [phone,fax,email,sms,pager,url,other]
  value?: string
  use?: string
  rank?:
    type: !include ../primitives/positiveInt.raml
  period?: !include ./Period.raml
