#%RAML 1.0 DataType

#This file is located at dataTypes/elements/Dosage.raml

description: How the medication is/was taken or should be taken
type: Element
properties:
  sequence?:
    description: The order of the dosage instructions
    type: integer
  text?:
    description: Free text dosage instructions e.g. SIG
    type: string
  additionalInstruction?:
    description: Supplemental instruction - e.g. "with meals"
    type: CodeableConcept[]
  patientInstruction?:
    description: Patient or consumer oriented instructions
    type: string
  timing?:
    description: When medication should be administered
    type: Timing
  asNeededBoolean?:
    description: Take "as needed"
    type: boolean
  asNeededCodeableConcept?:
    description: Take "as needed"
    type: CodeableConcept
  site?:
    description: Body site to administer to
    type: CodeableConcept
  route?:
    description: How drug should enter body
    type: CodeableConcept
  method?:
    description: Technique for administering medication
    type: CodeableConcept
  doseRange?:
    description: Amount of medication per dose
    type: Range
  doseQuantity?:
    description: Amount of medication per dose
    type: SimpleQuantity
  maxDosePerPeriod?:
    description: Upper limit on medication per unit of time
    type: Ratio
  maxDosePerAdministration?:
    description: Upper limit on medication per administration
    type: SimpleQuantity
  maxDosePerLifetime?:
    description: Upper limit on medication per lifetime of the patient
    type: SimpleQuantity
  rateRatio?:
    description: Amount of medication per unit of timen
    type: Ratio
  rateRange?:
    description: Amount of medication per unit of time
    type: Range
  rateQuantity?:
    description: Amount of medication per unit of time
    type: SimpleQuantity
