#%RAML 1.0 DataType

#This file is located at dataTypes/elements/Element.raml

type: object
properties:
  id?: !include ../primitives/id.raml
  extension?:
    type: array
    items: !include ./Extension.raml
