#%RAML 1.0 DataType

#This file is located at dataTypes/elements/HumanName.raml


type: !include ./Element.raml
description: |
  A name of a human with text, parts and usage information.
properties:
  use?:
    type: !include ../primitives/code.raml
    enum: [usual, official ,temp, nickname, anonymous, old, maiden]
  text?:
  family?: string[]
  given?: string[]
  prefix?: string[]
  suffix?: string[]
  period?: !include ./Period.raml
