#%RAML 1.0 DataType

#This file is located at dataTypes/elements/Period.raml


type: !include ./Element.raml
description: A time period defined by a start and end date/time.
properties:
  start?: !include ../primitives/dateTime.raml
  end?: !include ../primitives/dateTime.raml
