#%RAML 1.0 DataType

#This file is located at dataTypes/elements/Quantity.raml


type: !include ./Element.raml
description: A measured amount (or an amount that can potentially be measured).
properties:
  value?: !include ../primitives/decimal
  comparator?:
    type: !include ../primitives/code.raml
    enum: ['<', '<=', '>=', '>']
  unit?: string
  system?: !include ../primitives/uri.raml
  code?: !include ../primitives/code.raml
