#%RAML 1.0 DataType

#This file is located at dataTypes/elements/Ratio.raml


type: !include ./Element.raml
description: A relationship between two Quantity values expressed as a numerator and a denominator.
properties:
  numerator?: !include ./Quantity.raml
  denominator?: !include ./Quantity.raml
