#%RAML 1.0 DataType

#This file is located at dataTypes/elements/SampledData.raml


type: !include ./Element.raml
description: A series of measurements taken by a device
properties:
  origin: !include ./Quantity.raml
  period: !include ../primitives/decimal.raml
  factor?: !include ../primitives/decimal.raml
  lowerLimit?: !include ../primitives/decimal.raml
  upperLimit?: !include ../primitives/decimal.raml
  dimensions: !include ../primitives/positiveInt.raml
  data: string
