#%RAML 1.0 DataType

#This file is located at dataTypes/resources/Condition.raml


description: |
  Detailed information about conditions, problems or diagnoses
  + If condition is abated, then clinicalStatus must be either inactive, resolved, or remission
  + Condition.clinicalStatus SHALL be present if verificationStatus is not entered-in-error
type: DomainResource
properties:
  identifier?:
    description: External Ids for this condition
    type: Identifier[]
  clinicalStatus?:
    description: active | recurrence | inactive | remission | resolved
    type: code
    enum: [active, recurrence, inactive, remission, resolved]
  verificationStatus?:.
    description: provisional | differential | confirmed | refuted | entered-in-error | unknown
    type: code
    enum: [provisional, differential, confirmed, refuted, entered-in-error, unknown]
  category?:
    description: problem-list-item | encounter-diagnosis
    type: CodeableConcept[]
    enum: [problem-list-item, encounter-diagnosis]
  severity?:
    description: Subjective severity of condition
    type: CodeableConcept
  code?:
    description: Identification of the condition, problem or diagnosis
    type: CodeableConcept
  bodySite?:
    description: Anatomical location, if relevant
    type: CodeableConcept[]
  subject:
    description: Who has the condition?
    type: Reference
  context?:
    description: Encounter or episode when condition first asserted
    type: Reference
  onsetDateTime?:
    description: Estimated or actual date, date-time, or age
    type: dateTime
  onsetAge?:
    description: Estimated or actual date, date-time, or age
    type: Age
  onsetPeriod?:
    description: Estimated or actual date, date-time, or age
    type: Period
  onsetRange?:
    description: Estimated or actual date, date-time, or age
    type: Range
  onsetString?:
    description: Estimated or actual date, date-time, or age
    type: string
  abatementDateTime?:
    description: If/when in resolution/remission
    type: dateTime
  abatementAge?:
    description: If/when in resolution/remission
    type: Age
  abatementBoolean?:
    description: If/when in resolution/remission
    type: boolean
  abatementPeriod?:
    description: If/when in resolution/remission
    type: Period
  abatementRange?:
    description: If/when in resolution/remission
    type: Range
  abatementString?:
    description: If/when in resolution/remission
    type: string
  assertedDate?:
    description: Date record was believed accurate
    type: dateTime
  asserter?:
    description: Person who asserts this condition
    type: Reference
  stage?:
    description: |
      Stage/grade, usually assessed formally
      + Stage SHALL have summary or assessment
    type: BackboneElement
    properties:
      summary?:
        description: Simple summary (disease specific)
        type: CodeableConcept
      asessment?:
        description: Formal record of assessment
        type: Reference[]
  evidence?:
    description: |
      Supporting evidence
      + evidence SHALL have code or details
    type: array
    items:
      type: BackboneElement
      properties:
        code?:
          description: Manifestation/symptom
          type: CodeableConcept[]
        detail?:
          description: Supporting information found elsewhere
          type: Reference[]
  note?:
    description: Additional information about the Condition
    type: Annotation[]
