#%RAML 1.0 DataType

#This file is located at dataTypes/resources/Medication.raml


type: DomainResource
properties:
  code?: CodeableConcept
  status?:
    type: code
    enum: [active, inactive, entered-in-error]
  isBrand?: boolean
  isOverTheCounter?: boolean
  manufacturer?: Reference # Organization
  form?: 
    type: CodeableConcept # example powder, tablets, capsule
    enum: [powder, tablets, capsule]
  ingredient?:
    type: array
    items:
      type: BackboneElement
      properties:
        itemCodeableConcept?: CodeableConcept
        itemReference?: Reference
        isActive?: boolean
        amount?: Ratio
  package?:
    type: BackboneElement
    properties:
      container?: CodeableConcept
      content?:
        type: BackboneElement
        properties:
          item: Reference
          amount?: SimpleQuantity
      batch?:
        type: array
        items:
          type: BackboneElement
          properties:
            lotNumber?: string
            expirationDate?: dateTime
  image?:
    type: Array
    items:
      type: Attachment
