#%RAML 1.0 DataType

#This file is located at dataTypes/resources/Medication.raml

description: Definition of a Medication
type: DomainResource
properties:
  code?:
    description: Codes that identify this medication
    type: CodeableConcept
  status?:
    description: Medication status
    type: code
    enum: [active, inactive, entered-in-error]
  isBrand?:
    description: True if a brand
    type: boolean
  isOverTheCounter?:
    description: True if medication does not require a prescription
    type: boolean
  manufacturer?:
    description: Manufacturer of the item
    type: Reference
  form?:
    description: powder | tablets | capsule
    type: CodeableConcept
  ingredient?:
    description: Active or inactive ingredient
    type: array
    items:
      type: BackboneElement
      properties:
        itemCodeableConcept?:
          description: The product contained
          type: CodeableConcept
        itemReference?:
          description: The product contained
          type: Reference
        isActive?:
          description: Active ingredient indicator
          type: boolean
        amount?:
          description: Quantity of ingredient present
          type: Ratio
  package?:
    description: Details about packaged medications
    type: BackboneElement
    properties:
      container?:
        description: E.g. box, vial, blister-pack
        type: CodeableConcept
      content?:
        description: What is in the package
        type: array
        items:
          type: BackboneElement
          properties:
            itemCodeableConcept?:
              description: The item in the package
              type: CodeableConcept
            itemReference?:
              description: The item in the package
              type: Reference
            amount?:
              description: Quantity present in the package
              type: SimpleQuantity
      batch?:
        description: Identifies a single production run
        type: array
        items:
          type: BackboneElement
          properties:
            lotNumber?:
              description: Identifier assigned to batch
              type: string
            expirationDate?:
              description: When batch will expire
              type: dateTime
  image?:
    description: Picture of the medication
    type: Attachment[]
