#%RAML 1.0 DataType

#This file is located at dataTypes/resources/Practitioner.raml


type: DomainResource
description: |
  Practitioner covers all individuals who are engaged in the healthcare process and healthcare-related services as part of their formal responsibilities and this Resource is used for attribution of activities and responsibilities to these individuals.
properties:
  identifier?:
    description: A identifier for the person as this agent
    type: array
    items: Identifier
  active?:
    description: Whether this practitioner's record is in active use
    type: boolean
  name?:
    description: The name(s) associated with the practitioner
    type: array
    items: HumanName
  telecom?:
    description: A contact detail for the practitioner (that apply to all roles)
    type: array
    items: ContactPoint
  address?:
    description: Address(es) of the practitioner that are not role specific (typically home address)
    type: array
    items: Address
  gender?:
    description: Practitioner gender
    type: gender
    enum: [male, female, other, unknown]
  birthDate?:
    description: The date  on which the practitioner was born
    type: date
  photo?:
    description: Image of the person
    type: array
    items: Attachment
  qualification?:
    description: |
      Qualifications obtained by training and certification
    type: array
    items:
      type: BackboneElement
      properties:
        identifier?:
          description:
          type: array
          items: Identifier
        code:
          description: Coded representation of the qualification
          type: CodeableConcept
        period?:
          description: |
            Period during which the qualification is valid
          type: Period
        issuer?:
          description: Organization that regulates and issues the qualification
          type: Reference
  communication?:
    description: A language the practitioner is able to use in patient communication
    type: array
    items: CodeableConcept
