#%RAML 1.0 DataType

#This file is located at dataTypes/resources/Slot.raml


type: DomainResource
description: |
  A slot of time on a schedule that may be available for booking appointments
properties:
  identifier?:
    description: External Ids for this item
    type: array
    items: Identifier
  serviceCategory:
    description: A broad categorisation of the service that is to be performed during this appointment
    type: CodeableConcept
  serviceType:
    description: |
      The type of appointments that can be booked into this slot (ideally this would be an identifiable service - which is at a location, rather than the location itself).
      If provided then this overrides the value provided on the availability resource
    type: array
    items: CodeableConcept
  speciality:
    description: The specialty of a practitioner that would be required to perform the service requested in this appointment
    type: array
    items: CodeableConcept
  appointmentType:
    description: The style of appointment or patient that may be booked in the slot (not service type)
    type: CodeableConcept
  schedule:
    description: The schedule resource that this slot defines an interval of status information
    type: Reference
  status:
    description: Status of slot
    type: code
    enum: [busy, free, busy-unavailable, busy-tentative, entered-in-error]
  start:
    description: Date/Time that the slot is to begin
    type: instant
  end:
    description: Date/Time that the slot is to conclude
    type: instant
  overbooked?:
    description: This slot has already been overbooked, appointments are unlikely to be accepted for this time
    type: boolean
  comment?:
    description: Comments on the slot to describe any extended information. Such as custom constraints on the slot
    type: string
